name: "YouTube Stream Repeater HTTPS"
description: "YouTube Stream Repeater HTTPS"
version: "1.0.14"
slug: "yt_str_srv_https"
options:
  user: null
  password: null
schema:
  user: str
  password: str
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4443/tcp: 4443
map:
  - config:rw
  - ssl
