name: "Amule New"
description: "Amule Service"
version: "1.0.14"
slug: "amule_srv_new"
init: false
ingress: true
ingress_port: 4711
options:
  GUI_PWD:
  WEBUI_PWD:
  KAD_NODES_DAT_URL: http://upd.emule-security.org/nodes.dat
  MOD_AUTO_RESTART_ENABLED: true
schema:
  GUI_PWD: str
  WEBUI_PWD: str
  KAD_NODES_DAT_URL: str?
  MOD_AUTO_RESTART_ENABLED: bool?
init: false
environment:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Rome"
  MOD_AUTO_RESTART_CRON: "0 6 * * *"
  MOD_AUTO_SHARE_ENABLED: "false"
  MOD_AUTO_SHARE_DIRECTORIES: "/incoming;/my_movies"
  MOD_FIX_KAD_GRAPH_ENABLED: "true"
  MOD_FIX_KAD_BOOTSTRAP_ENABLED: "true"
  
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  4711/tcp: 4711 # web ui
  4712/tcp: 4712 # remote gui, webserver, cmd ...
  4662/tcp: 4662 # ed2k tcp
  4665/udp: 4665 # ed2k global search udp (tcp port +3)
  4672/udp: 4672 # ed2k udp